import test from 'node:test';import assert from 'node:assert/strict';import {transformWithEsbuild} from 'vite';import{readFile}from'node:fs/promises';
const compiled=await transformWithEsbuild(await readFile('src/lib/player-core.ts','utf8'),'core.ts',{loader:'ts',target:'es2022'});
const{createPlayer,emptyPlayerState}=await import('data:text/javascript;base64,'+Buffer.from(compiled.code).toString('base64'));
const tracks=[{id:'1',name:'first',duration:180},{id:'2',name:'second',duration:180}];const full=id=>({uid:'1001',track_id:id,status:'playable',url:'https://m7.music.126.net/'+id+'.mp3',expires_in:300,trial_start:0,trial_end:0,message:'标准音质'});
function setup(fetch=async id=>full(id)){let token='session-a';const drivers=[];const state=emptyPlayerState();const player=createPlayer(state,fetch,e=>{const d={events:e,loaded:'',plays:0,destroyed:false,seeks:[],load(url){this.loaded=url},async play(){this.plays++;e.play()},pause(){e.pause()},seek(s){this.seeks.push(s)},destroy(){this.destroyed=true;e.pause()}};drivers.push(d);return d},()=>token);player.setOwner('account-a');return{player,state,drivers,switchToken:t=>{token=t}}}
test('audio survives same-account refresh and is destroyed on account switch',async()=>{const x=setup();await x.player.select(tracks[0],tracks,'123');assert.equal(x.state.status,'playing');x.player.setOwner('account-a');assert.equal(x.drivers[0].destroyed,false);x.switchToken('session-b');x.player.setOwner('account-b');assert.equal(x.state.track,null);assert.equal(x.drivers[0].destroyed,true)});
test('late playback URL after close/logout cannot start audio',async()=>{let resolve;const x=setup(()=>new Promise(r=>resolve=r));const pending=x.player.select(tracks[0],tracks,'123');x.player.reset();resolve(full('1'));await pending;assert.equal(x.drivers.length,0);assert.equal(x.state.track,null)});
test('rapid switching ignores older request and uses newest track',async()=>{const pending={};const x=setup(id=>new Promise(r=>pending[id]=r));const a=x.player.select(tracks[0],tracks,'123');const b=x.player.select(tracks[1],tracks,'123');pending['2'](full('2'));await b;pending['1'](full('1'));await a;assert.equal(x.drivers.length,1);assert.equal(x.state.track.id,'2');assert.equal(x.drivers[0].loaded,full('2').url)});
test('pausing while loading cancels pending autoplay',async()=>{let resolve;const x=setup(()=>new Promise(r=>resolve=r));const pending=x.player.select(tracks[0],tracks,'123');x.player.pause();resolve(full('1'));await pending;assert.equal(x.drivers.length,0);assert.equal(x.state.status,'paused')});
test('trial seeks stay within allowed segment and stop at end',async()=>{const x=setup(async id=>({...full(id),status:'trial',trial_start:60,trial_end:90}));await x.player.select(tracks[0],[tracks[0]],'123');const d=x.drivers[0];d.events.meta(180);d.events.meta(180);assert.deepEqual(d.seeks,[60]);assert.equal(x.state.duration,30);x.player.seek(100);assert.ok(d.seeks.at(-1)<90);x.player.seek(-5);assert.equal(d.seeks.at(-1),60);d.events.time(90);assert.equal(x.state.status,'ended')});
test('already clipped preview starts at zero and browser gesture retry reuses source',async()=>{const x=setup(async id=>({...full(id),status:'trial',trial_start:60,trial_end:90}));await x.player.select(tracks[0],[tracks[0]],'123');const d=x.drivers[0];d.events.meta(30);x.player.seek(10);assert.equal(d.seeks.at(-1),10);d.play=async()=>{throw Error('NotAllowedError')};x.player.pause();x.player.toggle();await new Promise(r=>setImmediate(r));assert.equal(x.state.status,'blocked');d.play=async()=>d.events.play();x.player.toggle();await new Promise(r=>setImmediate(r));assert.equal(x.state.status,'playing');assert.equal(x.drivers.length,1)});
test('unavailable tracks do not load or substitute audio',async()=>{const x=setup(async()=>({status:'unavailable',message:'权限不足',url:''}));await x.player.select(tracks[0],tracks,'123');assert.equal(x.state.status,'unavailable');assert.equal(x.drivers.length,0)});
test('normal end advances to next track; paused audio resumes without another URL request',async()=>{let calls=0;const x=setup(async id=>{calls++;return full(id)});await x.player.select(tracks[0],tracks,'123');x.player.pause();x.player.toggle();await new Promise(r=>setImmediate(r));assert.equal(calls,1);x.drivers[0].events.ended();await new Promise(r=>setImmediate(r));assert.equal(x.state.track.id,'2');assert.equal(calls,2)});
